services:
  bids.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Bids.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55wordHello"
  
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" 
    depends_on: 
      - client
      - bids.api
  
  
  client: 
    build:
      context: ./bids.client
      dockerfile: Dockerfile
    volumes:
      - ./bids.client:/app
    ports:
      - "5001:3000"
    depends_on: 
      - bids.api